// Indian passenger-vehicle catalog (≈2010–2026).
// Purpose: clean make/model selection + body/fuel/segment for valuation adjustments.
// NOT a price table — the valuation engine anchors on IDV, so no prices are stored here.
// Manual entry remains open in the app for anything missing.
// body: HATCHBACK | SEDAN | SUV | MUV | LUXURY | EV
// segment: A (entry) | B (compact) | C (mid) | D (premium) | E (luxury)
// fuels: subset of PETROL,DIESEL,CNG,HYBRID,ELECTRIC

export interface CatalogModel {
  model: string;
  body: string;
  segment: string;
  fuels: string[];
  from: number;
  to: number | null; // null = still on sale
}
export interface CatalogMake { make: string; models: CatalogModel[]; }

const P = "PETROL", D = "DIESEL", C = "CNG", H = "HYBRID", E = "ELECTRIC";

export const VEHICLE_CATALOG: CatalogMake[] = [
  { make: "MARUTI SUZUKI", models: [
    { model: "Alto 800", body: "HATCHBACK", segment: "A", fuels: [P, C], from: 2012, to: 2022 },
    { model: "Alto K10", body: "HATCHBACK", segment: "A", fuels: [P, C], from: 2010, to: null },
    { model: "S-Presso", body: "HATCHBACK", segment: "A", fuels: [P, C], from: 2019, to: null },
    { model: "Celerio", body: "HATCHBACK", segment: "A", fuels: [P, C], from: 2014, to: null },
    { model: "WagonR", body: "HATCHBACK", segment: "A", fuels: [P, C], from: 2010, to: null },
    { model: "Swift", body: "HATCHBACK", segment: "B", fuels: [P, D, C], from: 2010, to: null },
    { model: "Ignis", body: "HATCHBACK", segment: "B", fuels: [P], from: 2017, to: null },
    { model: "Baleno", body: "HATCHBACK", segment: "B", fuels: [P, D, C], from: 2015, to: null },
    { model: "Ritz", body: "HATCHBACK", segment: "B", fuels: [P, D], from: 2010, to: 2017 },
    { model: "A-Star", body: "HATCHBACK", segment: "A", fuels: [P], from: 2010, to: 2014 },
    { model: "Zen Estilo", body: "HATCHBACK", segment: "A", fuels: [P, C], from: 2010, to: 2013 },
    { model: "Dzire", body: "SEDAN", segment: "B", fuels: [P, D, C], from: 2010, to: null },
    { model: "Swift Dzire", body: "SEDAN", segment: "B", fuels: [P, D], from: 2010, to: 2017 },
    { model: "Ciaz", body: "SEDAN", segment: "C", fuels: [P, D, H], from: 2014, to: null },
    { model: "SX4", body: "SEDAN", segment: "C", fuels: [P], from: 2010, to: 2014 },
    { model: "Kizashi", body: "SEDAN", segment: "D", fuels: [P], from: 2011, to: 2014 },
    { model: "Fronx", body: "SUV", segment: "B", fuels: [P, C], from: 2023, to: null },
    { model: "Brezza", body: "SUV", segment: "B", fuels: [P, C], from: 2016, to: null },
    { model: "Vitara Brezza", body: "SUV", segment: "B", fuels: [P, D], from: 2016, to: 2022 },
    { model: "Grand Vitara", body: "SUV", segment: "C", fuels: [P, H, C], from: 2022, to: null },
    { model: "S-Cross", body: "SUV", segment: "C", fuels: [P, D], from: 2015, to: 2022 },
    { model: "Jimny", body: "SUV", segment: "B", fuels: [P], from: 2023, to: null },
    { model: "Gypsy", body: "SUV", segment: "B", fuels: [P], from: 2010, to: 2018 },
    { model: "Ertiga", body: "MUV", segment: "C", fuels: [P, D, C], from: 2012, to: null },
    { model: "XL6", body: "MUV", segment: "C", fuels: [P, C], from: 2019, to: null },
    { model: "Eeco", body: "MUV", segment: "A", fuels: [P, C], from: 2010, to: null },
    { model: "Omni", body: "MUV", segment: "A", fuels: [P, C], from: 2010, to: 2019 },
    { model: "Invicto", body: "MUV", segment: "D", fuels: [H], from: 2023, to: null },
    { model: "e-Vitara", body: "EV", segment: "C", fuels: [E], from: 2025, to: null },
  ]},
  { make: "HYUNDAI", models: [
    { model: "Santro", body: "HATCHBACK", segment: "A", fuels: [P, C], from: 2010, to: 2022 },
    { model: "Eon", body: "HATCHBACK", segment: "A", fuels: [P], from: 2011, to: 2019 },
    { model: "i10", body: "HATCHBACK", segment: "A", fuels: [P], from: 2010, to: 2017 },
    { model: "Grand i10", body: "HATCHBACK", segment: "B", fuels: [P, D, C], from: 2013, to: 2020 },
    { model: "Grand i10 Nios", body: "HATCHBACK", segment: "B", fuels: [P, C], from: 2019, to: null },
    { model: "i20", body: "HATCHBACK", segment: "B", fuels: [P, D], from: 2010, to: null },
    { model: "i20 Active", body: "HATCHBACK", segment: "B", fuels: [P, D], from: 2015, to: 2020 },
    { model: "Xcent", body: "SEDAN", segment: "B", fuels: [P, D, C], from: 2014, to: 2019 },
    { model: "Aura", body: "SEDAN", segment: "B", fuels: [P, C], from: 2020, to: null },
    { model: "Verna", body: "SEDAN", segment: "C", fuels: [P, D], from: 2010, to: null },
    { model: "Elantra", body: "SEDAN", segment: "D", fuels: [P, D], from: 2012, to: 2022 },
    { model: "Exter", body: "SUV", segment: "B", fuels: [P, C], from: 2023, to: null },
    { model: "Venue", body: "SUV", segment: "B", fuels: [P, D], from: 2019, to: null },
    { model: "Creta", body: "SUV", segment: "C", fuels: [P, D, E], from: 2015, to: null },
    { model: "Alcazar", body: "SUV", segment: "C", fuels: [P, D], from: 2021, to: null },
    { model: "Tucson", body: "SUV", segment: "D", fuels: [P, D], from: 2016, to: null },
    { model: "Kona Electric", body: "EV", segment: "C", fuels: [E], from: 2019, to: 2024 },
    { model: "Ioniq 5", body: "EV", segment: "D", fuels: [E], from: 2022, to: null },
  ]},
  { make: "TATA", models: [
    { model: "Nano", body: "HATCHBACK", segment: "A", fuels: [P], from: 2010, to: 2018 },
    { model: "Indica", body: "HATCHBACK", segment: "B", fuels: [P, D], from: 2010, to: 2018 },
    { model: "Bolt", body: "HATCHBACK", segment: "B", fuels: [P, D], from: 2014, to: 2019 },
    { model: "Tiago", body: "HATCHBACK", segment: "B", fuels: [P, C, E], from: 2016, to: null },
    { model: "Altroz", body: "HATCHBACK", segment: "B", fuels: [P, D, C], from: 2020, to: null },
    { model: "Indigo", body: "SEDAN", segment: "B", fuels: [P, D], from: 2010, to: 2018 },
    { model: "Zest", body: "SEDAN", segment: "B", fuels: [P, D], from: 2014, to: 2019 },
    { model: "Tigor", body: "SEDAN", segment: "B", fuels: [P, C, E], from: 2017, to: null },
    { model: "Punch", body: "SUV", segment: "B", fuels: [P, C, E], from: 2021, to: null },
    { model: "Nexon", body: "SUV", segment: "B", fuels: [P, D, C, E], from: 2017, to: null },
    { model: "Curvv", body: "SUV", segment: "C", fuels: [P, D, E], from: 2024, to: null },
    { model: "Harrier", body: "SUV", segment: "C", fuels: [D, P, E], from: 2019, to: null },
    { model: "Safari", body: "SUV", segment: "C", fuels: [D, P, E], from: 2021, to: null },
    { model: "Safari Storme", body: "SUV", segment: "C", fuels: [D], from: 2012, to: 2019 },
    { model: "Sierra", body: "SUV", segment: "C", fuels: [P, E], from: 2025, to: null },
    { model: "Hexa", body: "MUV", segment: "C", fuels: [D], from: 2017, to: 2020 },
    { model: "Sumo", body: "MUV", segment: "B", fuels: [D], from: 2010, to: 2019 },
    { model: "Aria", body: "MUV", segment: "C", fuels: [D], from: 2010, to: 2017 },
    { model: "Tiago EV", body: "EV", segment: "B", fuels: [E], from: 2022, to: null },
    { model: "Punch EV", body: "EV", segment: "B", fuels: [E], from: 2024, to: null },
  ]},
  { make: "MAHINDRA", models: [
    { model: "Bolero", body: "SUV", segment: "B", fuels: [D], from: 2010, to: null },
    { model: "Bolero Neo", body: "SUV", segment: "B", fuels: [D], from: 2021, to: null },
    { model: "Thar", body: "SUV", segment: "B", fuels: [P, D], from: 2010, to: null },
    { model: "Thar Roxx", body: "SUV", segment: "C", fuels: [P, D], from: 2024, to: null },
    { model: "XUV300", body: "SUV", segment: "B", fuels: [P, D], from: 2019, to: 2024 },
    { model: "XUV 3XO", body: "SUV", segment: "B", fuels: [P, D], from: 2024, to: null },
    { model: "Scorpio", body: "SUV", segment: "C", fuels: [D], from: 2010, to: null },
    { model: "Scorpio N", body: "SUV", segment: "C", fuels: [P, D], from: 2022, to: null },
    { model: "Scorpio Classic", body: "SUV", segment: "C", fuels: [D], from: 2022, to: null },
    { model: "XUV500", body: "SUV", segment: "C", fuels: [D], from: 2011, to: 2021 },
    { model: "XUV700", body: "SUV", segment: "C", fuels: [P, D], from: 2021, to: null },
    { model: "Quanto", body: "SUV", segment: "B", fuels: [D], from: 2012, to: 2016 },
    { model: "TUV300", body: "SUV", segment: "B", fuels: [D], from: 2015, to: 2020 },
    { model: "KUV100", body: "SUV", segment: "A", fuels: [P, D], from: 2016, to: 2023 },
    { model: "Marazzo", body: "MUV", segment: "C", fuels: [D], from: 2018, to: 2024 },
    { model: "Xylo", body: "MUV", segment: "C", fuels: [D], from: 2010, to: 2019 },
    { model: "Verito", body: "SEDAN", segment: "B", fuels: [P, D], from: 2010, to: 2018 },
    { model: "BE 6", body: "EV", segment: "C", fuels: [E], from: 2025, to: null },
    { model: "XEV 9e", body: "EV", segment: "C", fuels: [E], from: 2025, to: null },
    { model: "XUV400 EV", body: "EV", segment: "B", fuels: [E], from: 2023, to: null },
    { model: "e2o", body: "EV", segment: "A", fuels: [E], from: 2013, to: 2019 },
  ]},
  { make: "TOYOTA", models: [
    { model: "Etios", body: "SEDAN", segment: "B", fuels: [P, D], from: 2010, to: 2020 },
    { model: "Etios Liva", body: "HATCHBACK", segment: "B", fuels: [P, D], from: 2011, to: 2020 },
    { model: "Etios Cross", body: "HATCHBACK", segment: "B", fuels: [P, D], from: 2014, to: 2020 },
    { model: "Glanza", body: "HATCHBACK", segment: "B", fuels: [P, C], from: 2019, to: null },
    { model: "Yaris", body: "SEDAN", segment: "C", fuels: [P], from: 2018, to: 2022 },
    { model: "Corolla Altis", body: "SEDAN", segment: "D", fuels: [P, D], from: 2010, to: 2020 },
    { model: "Camry", body: "SEDAN", segment: "E", fuels: [P, H], from: 2010, to: null },
    { model: "Taisor", body: "SUV", segment: "B", fuels: [P, C], from: 2024, to: null },
    { model: "Urban Cruiser", body: "SUV", segment: "B", fuels: [P], from: 2020, to: 2022 },
    { model: "Urban Cruiser Hyryder", body: "SUV", segment: "C", fuels: [P, H, C], from: 2022, to: null },
    { model: "Fortuner", body: "SUV", segment: "D", fuels: [D, P], from: 2010, to: null },
    { model: "Legender", body: "SUV", segment: "D", fuels: [D], from: 2021, to: null },
    { model: "Land Cruiser", body: "SUV", segment: "E", fuels: [D], from: 2010, to: null },
    { model: "Innova", body: "MUV", segment: "C", fuels: [D, P], from: 2010, to: 2016 },
    { model: "Innova Crysta", body: "MUV", segment: "C", fuels: [D, P], from: 2016, to: null },
    { model: "Innova Hycross", body: "MUV", segment: "D", fuels: [P, H], from: 2023, to: null },
    { model: "Rumion", body: "MUV", segment: "C", fuels: [P, C], from: 2023, to: null },
    { model: "Vellfire", body: "MUV", segment: "E", fuels: [H], from: 2020, to: null },
  ]},
  { make: "KIA", models: [
    { model: "Sonet", body: "SUV", segment: "B", fuels: [P, D], from: 2020, to: null },
    { model: "Syros", body: "SUV", segment: "B", fuels: [P, D], from: 2025, to: null },
    { model: "Seltos", body: "SUV", segment: "C", fuels: [P, D], from: 2019, to: null },
    { model: "Carens", body: "MUV", segment: "C", fuels: [P, D], from: 2022, to: null },
    { model: "Carens Clavis", body: "MUV", segment: "C", fuels: [P, D], from: 2025, to: null },
    { model: "Carnival", body: "MUV", segment: "E", fuels: [D], from: 2020, to: null },
    { model: "EV6", body: "EV", segment: "D", fuels: [E], from: 2022, to: null },
    { model: "Carens Clavis EV", body: "EV", segment: "C", fuels: [E], from: 2025, to: null },
  ]},
  { make: "HONDA", models: [
    { model: "Brio", body: "HATCHBACK", segment: "B", fuels: [P], from: 2011, to: 2018 },
    { model: "Jazz", body: "HATCHBACK", segment: "B", fuels: [P, D], from: 2010, to: 2022 },
    { model: "WR-V", body: "HATCHBACK", segment: "B", fuels: [P, D], from: 2017, to: 2023 },
    { model: "Amaze", body: "SEDAN", segment: "B", fuels: [P, D], from: 2013, to: null },
    { model: "City", body: "SEDAN", segment: "C", fuels: [P, D, H], from: 2010, to: null },
    { model: "Civic", body: "SEDAN", segment: "D", fuels: [P, D], from: 2010, to: 2020 },
    { model: "Accord", body: "SEDAN", segment: "E", fuels: [P, H], from: 2010, to: 2020 },
    { model: "Mobilio", body: "MUV", segment: "C", fuels: [P, D], from: 2014, to: 2017 },
    { model: "BR-V", body: "SUV", segment: "C", fuels: [P, D], from: 2016, to: 2020 },
    { model: "Elevate", body: "SUV", segment: "C", fuels: [P], from: 2023, to: null },
  ]},
  { make: "MG", models: [
    { model: "Hector", body: "SUV", segment: "C", fuels: [P, D, H], from: 2019, to: null },
    { model: "Hector Plus", body: "SUV", segment: "C", fuels: [P, D, H], from: 2020, to: null },
    { model: "Astor", body: "SUV", segment: "C", fuels: [P], from: 2021, to: null },
    { model: "Gloster", body: "SUV", segment: "E", fuels: [D], from: 2020, to: null },
    { model: "ZS EV", body: "EV", segment: "C", fuels: [E], from: 2020, to: null },
    { model: "Comet EV", body: "EV", segment: "A", fuels: [E], from: 2023, to: null },
    { model: "Windsor EV", body: "EV", segment: "C", fuels: [E], from: 2024, to: null },
  ]},
  { make: "SKODA", models: [
    { model: "Fabia", body: "HATCHBACK", segment: "B", fuels: [P, D], from: 2010, to: 2013 },
    { model: "Rapid", body: "SEDAN", segment: "C", fuels: [P, D], from: 2011, to: 2022 },
    { model: "Slavia", body: "SEDAN", segment: "C", fuels: [P], from: 2022, to: null },
    { model: "Octavia", body: "SEDAN", segment: "D", fuels: [P, D], from: 2010, to: 2024 },
    { model: "Superb", body: "SEDAN", segment: "E", fuels: [P, D], from: 2010, to: null },
    { model: "Kushaq", body: "SUV", segment: "C", fuels: [P], from: 2021, to: null },
    { model: "Kylaq", body: "SUV", segment: "B", fuels: [P], from: 2025, to: null },
    { model: "Kodiaq", body: "SUV", segment: "D", fuels: [P, D], from: 2017, to: null },
    { model: "Yeti", body: "SUV", segment: "C", fuels: [D], from: 2010, to: 2017 },
  ]},
  { make: "VOLKSWAGEN", models: [
    { model: "Polo", body: "HATCHBACK", segment: "B", fuels: [P, D], from: 2010, to: 2022 },
    { model: "Vento", body: "SEDAN", segment: "C", fuels: [P, D], from: 2010, to: 2022 },
    { model: "Virtus", body: "SEDAN", segment: "C", fuels: [P], from: 2022, to: null },
    { model: "Ameo", body: "SEDAN", segment: "B", fuels: [P, D], from: 2016, to: 2020 },
    { model: "Taigun", body: "SUV", segment: "C", fuels: [P], from: 2021, to: null },
    { model: "Tiguan", body: "SUV", segment: "D", fuels: [P, D], from: 2017, to: null },
    { model: "T-Roc", body: "SUV", segment: "D", fuels: [P], from: 2020, to: 2022 },
  ]},
  { make: "RENAULT", models: [
    { model: "Kwid", body: "HATCHBACK", segment: "A", fuels: [P, C], from: 2015, to: null },
    { model: "Pulse", body: "HATCHBACK", segment: "B", fuels: [P, D], from: 2012, to: 2017 },
    { model: "Triber", body: "MUV", segment: "B", fuels: [P, C], from: 2019, to: null },
    { model: "Kiger", body: "SUV", segment: "B", fuels: [P], from: 2021, to: null },
    { model: "Duster", body: "SUV", segment: "C", fuels: [P, D], from: 2012, to: 2022 },
    { model: "Captur", body: "SUV", segment: "C", fuels: [P, D], from: 2017, to: 2020 },
    { model: "Scala", body: "SEDAN", segment: "C", fuels: [P, D], from: 2012, to: 2017 },
    { model: "Lodgy", body: "MUV", segment: "C", fuels: [D], from: 2015, to: 2020 },
  ]},
  { make: "NISSAN", models: [
    { model: "Micra", body: "HATCHBACK", segment: "B", fuels: [P, D], from: 2010, to: 2020 },
    { model: "Sunny", body: "SEDAN", segment: "C", fuels: [P, D], from: 2011, to: 2020 },
    { model: "Magnite", body: "SUV", segment: "B", fuels: [P], from: 2020, to: null },
    { model: "Kicks", body: "SUV", segment: "C", fuels: [P], from: 2019, to: 2022 },
    { model: "Terrano", body: "SUV", segment: "C", fuels: [P, D], from: 2013, to: 2020 },
  ]},
  { make: "FORD", models: [
    { model: "Figo", body: "HATCHBACK", segment: "B", fuels: [P, D], from: 2010, to: 2021 },
    { model: "Figo Aspire", body: "SEDAN", segment: "B", fuels: [P, D], from: 2015, to: 2021 },
    { model: "Aspire", body: "SEDAN", segment: "B", fuels: [P, D], from: 2015, to: 2021 },
    { model: "Fiesta", body: "SEDAN", segment: "C", fuels: [P, D], from: 2010, to: 2015 },
    { model: "Classic", body: "SEDAN", segment: "C", fuels: [P, D], from: 2010, to: 2015 },
    { model: "EcoSport", body: "SUV", segment: "B", fuels: [P, D], from: 2013, to: 2021 },
    { model: "Freestyle", body: "HATCHBACK", segment: "B", fuels: [P, D], from: 2018, to: 2021 },
    { model: "Endeavour", body: "SUV", segment: "D", fuels: [D], from: 2010, to: 2021 },
  ]},
  { make: "CHEVROLET", models: [
    { model: "Spark", body: "HATCHBACK", segment: "A", fuels: [P], from: 2010, to: 2017 },
    { model: "Beat", body: "HATCHBACK", segment: "B", fuels: [P, D], from: 2010, to: 2017 },
    { model: "Sail", body: "SEDAN", segment: "B", fuels: [P, D], from: 2013, to: 2017 },
    { model: "Cruze", body: "SEDAN", segment: "D", fuels: [D], from: 2010, to: 2017 },
    { model: "Tavera", body: "MUV", segment: "C", fuels: [D], from: 2010, to: 2017 },
    { model: "Enjoy", body: "MUV", segment: "C", fuels: [P, D], from: 2013, to: 2017 },
  ]},
  { make: "DATSUN", models: [
    { model: "Go", body: "HATCHBACK", segment: "A", fuels: [P], from: 2014, to: 2022 },
    { model: "Go+", body: "MUV", segment: "A", fuels: [P], from: 2015, to: 2022 },
    { model: "Redi-Go", body: "HATCHBACK", segment: "A", fuels: [P], from: 2016, to: 2022 },
  ]},
  { make: "CITROEN", models: [
    { model: "C3", body: "HATCHBACK", segment: "B", fuels: [P], from: 2022, to: null },
    { model: "C3 Aircross", body: "SUV", segment: "C", fuels: [P], from: 2023, to: null },
    { model: "Basalt", body: "SUV", segment: "C", fuels: [P], from: 2024, to: null },
    { model: "eC3", body: "EV", segment: "B", fuels: [E], from: 2023, to: null },
  ]},
  { make: "JEEP", models: [
    { model: "Compass", body: "SUV", segment: "D", fuels: [P, D], from: 2017, to: null },
    { model: "Meridian", body: "SUV", segment: "D", fuels: [D], from: 2022, to: null },
    { model: "Wrangler", body: "SUV", segment: "E", fuels: [P], from: 2016, to: null },
  ]},
  { make: "BYD", models: [
    { model: "Atto 3", body: "EV", segment: "C", fuels: [E], from: 2022, to: null },
    { model: "Seal", body: "EV", segment: "D", fuels: [E], from: 2024, to: null },
    { model: "eMAX 7", body: "EV", segment: "C", fuels: [E], from: 2025, to: null },
  ]},
  { make: "FIAT", models: [
    { model: "Punto", body: "HATCHBACK", segment: "B", fuels: [P, D], from: 2010, to: 2018 },
    { model: "Linea", body: "SEDAN", segment: "C", fuels: [P, D], from: 2010, to: 2018 },
    { model: "Avventura", body: "HATCHBACK", segment: "B", fuels: [P, D], from: 2014, to: 2018 },
  ]},
];

// Flattened rows for DB seeding.
export function catalogRows(): { make: string; model: string; body: string; segment: string; fuels: string; year_from: number; year_to: number | null }[] {
  const rows: any[] = [];
  for (const mk of VEHICLE_CATALOG)
    for (const m of mk.models)
      rows.push({ make: mk.make, model: m.model, body: m.body, segment: m.segment, fuels: m.fuels.join(","), year_from: m.from, year_to: m.to });
  return rows;
}
